from rest_framework.response import Response
from rest_framework.decorators import api_view
import random

@api_view(['GET'])
def voter_cards(request):
    voter_deck = [
        {"noOfVoters": 1, "resources": ["power", "power", "reform"]},
        {"noOfVoters": 1, "resources": ["power", "power", "vision"]},
        {"noOfVoters": 1, "resources": ["power", "power", "wealth"]},
        {"noOfVoters": 1, "resources": ["reform", "reform", "power"]},
        {"noOfVoters": 1, "resources": ["reform", "reform", "vision"]},
        {"noOfVoters": 1, "resources": ["reform", "reform", "wealth"]},
        {"noOfVoters": 1, "resources": ["vision", "vision", "power"]},
        {"noOfVoters": 1, "resources": ["vision", "vision", "reform"]},
        {"noOfVoters": 1, "resources": ["vision", "vision", "wealth"]},
        {"noOfVoters": 1, "resources": ["wealth", "wealth", "power"]},
        {"noOfVoters": 1, "resources": ["wealth", "wealth", "reform"]},
        {"noOfVoters": 1, "resources": ["wealth", "wealth", "vision"]},
        {"noOfVoters": 1, "resources": ["power", "reform", "vision"]},
        {"noOfVoters": 1, "resources": ["power", "reform", "wealth"]},
        {"noOfVoters": 1, "resources": ["power", "vision", "wealth"]},
        {"noOfVoters": 1, "resources": ["reform", "vision", "wealth"]},
        {"noOfVoters": 2, "resources": ["power", "power", "reform", "vision"]},
        {"noOfVoters": 2, "resources": ["power", "power", "reform", "wealth"]},
        {"noOfVoters": 2, "resources": ["power", "power", "vision", "wealth"]},
        {"noOfVoters": 2, "resources": ["reform", "reform", "power", "vision"]},
        {"noOfVoters": 2, "resources": ["reform", "reform", "power", "wealth"]},
        {"noOfVoters": 2, "resources": ["reform", "reform", "vision", "wealth"]},
        {"noOfVoters": 2, "resources": ["vision", "vision", "power", "reform"]},
        {"noOfVoters": 2, "resources": ["vision", "vision", "power", "wealth"]},
        {"noOfVoters": 2, "resources": ["vision", "vision", "reform", "wealth"]},
        {"noOfVoters": 2, "resources": ["wealth", "wealth", "power", "reform"]},
        {"noOfVoters": 2, "resources": ["wealth", "wealth", "power", "vision"]},
        {"noOfVoters": 2, "resources": ["wealth", "wealth", "reform", "vision"]},
        {"noOfVoters": 2, "resources": ["power", "power", "reform", "reform"]},
        {"noOfVoters": 2, "resources": ["power", "power", "vision", "vision"]},
        {"noOfVoters": 2, "resources": ["power", "power", "wealth", "wealth"]},
        {"noOfVoters": 2, "resources": ["reform", "reform", "vision", "vision"]},
        {"noOfVoters": 2, "resources": ["reform", "reform", "wealth", "wealth"]},
        {"noOfVoters": 2, "resources": ["vision", "vision", "wealth", "wealth"]},
        {"noOfVoters": 2, "resources": ["power", "reform", "vision", "wealth"]},
        {"noOfVoters": 3, "resources": ["power", "power", "reform", "vision", "wealth"]},
        {"noOfVoters": 3, "resources": ["reform", "reform", "power", "vision", "wealth"]},
        {"noOfVoters": 3, "resources": ["vision", "vision", "power", "reform", "wealth"]},
        {"noOfVoters": 3, "resources": ["wealth", "wealth", "power", "reform", "vision"]},
        {"noOfVoters": 3, "resources": ["power", "power", "reform", "reform", "vision"]},
        {"noOfVoters": 3, "resources": ["power", "power", "reform", "reform", "wealth"]},
        {"noOfVoters": 3, "resources": ["power", "power", "vision", "vision", "reform"]},
        {"noOfVoters": 3, "resources": ["power", "power", "vision", "vision", "wealth"]},
        {"noOfVoters": 3, "resources": ["power", "power", "wealth", "wealth", "reform"]},
        {"noOfVoters": 3, "resources": ["power", "power", "wealth", "wealth", "vision"]},
        {"noOfVoters": 3, "resources": ["reform", "reform", "vision", "vision", "power"]},
        {"noOfVoters": 3, "resources": ["reform", "reform", "vision", "vision", "wealth"]},
        {"noOfVoters": 3, "resources": ["reform", "reform", "wealth", "wealth", "power"]},
        {"noOfVoters": 3, "resources": ["reform", "reform", "wealth", "wealth", "vision"]},
        {"noOfVoters": 3, "resources": ["vision", "vision", "wealth", "wealth", "power"]},
        {"noOfVoters": 3, "resources": ["vision", "vision", "wealth", "wealth", "reform"]},
        {"noOfVoters": 3, "resources": ["power", "reform", "vision", "wealth", "any"]},
        {"noOfVoters": 3, "resources": ["power", "reform", "vision", "wealth", "any"]},
        {"noOfVoters": 3, "resources": ["power", "reform", "vision", "wealth", "any"]},
        {"noOfVoters": 3, "resources": ["power", "reform", "vision", "wealth", "any"]},
    ]
    random.shuffle(voter_deck)
    return Response(voter_deck)
